name: FancyHolograms
main: de.oliver.FancyHolograms
author: OliverHD
version: 1.0.4
api-version: 1.19
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - FancyNpcs
commands:
  Hologram:
    permission: FancyHolograms.admin
    description: Main command for the FancyHolograms plugin
    aliases:
      - holograms
      - holo