name: FancyHolograms
main: de.oliver.fancyholograms.FancyHolograms
author: OliverHD
version: 1.0.6
api-version: 1.19
folia-supported: true
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - FancyNpcs
  - MiniPlaceholders
commands:
  FancyHolograms:
    permission: FancyHolograms.admin
  Hologram:
    permission: FancyHolograms.admin
    description: Main command for the FancyHolograms plugin
    aliases:
      - holograms
      - holo