name: Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'liberica'
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: shadowjar
          gradle-version: 8.7
      - uses: actions/upload-artifact@v4
        with:
          name: AEnchantments
          path: "AEnchantments/build/libs/*.jar"
